# =========================================================
# 🩻 CHEST X-RAY AI WEB - FINAL OPTIMIZED VERSION
# FastAPI + YOLOv8 + PDF Export + Railway/Render Ready
# =========================================================

from fastapi import FastAPI, UploadFile, File
from fastapi.responses import HTMLResponse, FileResponse
from ultralytics import YOLO
from PIL import Image
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Image as PDFImage,
    Table,
    TableStyle
)
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import A4

import uvicorn
import shutil
import base64
import os

# =========================================================
# FASTAPI
# =========================================================

app = FastAPI()

# =========================================================
# LOAD MODEL
# =========================================================

model = YOLO("best.pt")

# =========================================================
# PREDICTION FUNCTION
# =========================================================

def run_prediction(img_path):

    results = model(
        img_path,
        imgsz=640,
        conf=0.25,
        verbose=False
    )[0]

    boxes = results.boxes

    predictions = []

    for box in boxes:
        cls = int(box.cls[0])
        conf = float(box.conf[0]) * 100
        name = model.names[cls]

        predictions.append({
            "name": name,
            "conf": round(conf, 2)
        })

    result_path = "result.jpg"
    results.save(result_path)

    return result_path, predictions

# =========================================================
# PDF REPORT
# =========================================================

def generate_pdf(input_img, result_img, predictions):

    doc = SimpleDocTemplate(
        "report.pdf",
        pagesize=A4
    )

    styles = getSampleStyleSheet()
    story = []

    # TITLE
    title = Paragraph(
        "Chest X-ray AI Detection Report",
        styles['Title']
    )

    story.append(title)
    story.append(Spacer(1, 20))

    # INPUT IMAGE
    story.append(
        Paragraph("Input X-ray Image", styles['Heading2'])
    )

    story.append(
        PDFImage(input_img, width=400, height=300)
    )

    story.append(Spacer(1, 20))

    # RESULT IMAGE
    story.append(
        Paragraph("AI Detection Result", styles['Heading2'])
    )

    story.append(
        PDFImage(result_img, width=400, height=300)
    )

    story.append(Spacer(1, 20))

    # TABLE
    table_data = [["Disease", "Confidence %"]]

    if len(predictions) == 0:
        table_data.append(["No abnormality detected", "100%"])
    else:
        for p in predictions:
            table_data.append([
                p["name"],
                f'{p["conf"]}%'
            ])

    table = Table(table_data, colWidths=[250, 150])

    table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.darkblue),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('GRID', (0,0), (-1,-1), 1, colors.grey),
        ('BOTTOMPADDING', (0,0), (-1,0), 12),
    ]))

    story.append(table)
    story.append(Spacer(1, 25))

    # DISCLAIMER
    disclaimer = Paragraph(
        "<i>This report is generated by AI for educational and research purposes only.</i>",
        styles['Italic']
    )

    story.append(disclaimer)

    doc.build(story)

# =========================================================
# HOME PAGE
# =========================================================

@app.get("/", response_class=HTMLResponse)
def home():

    return """
<!DOCTYPE html>
<html>

<head>

<title>Xray AI</title>

<style>

body{
    margin:0;
    font-family:Segoe UI;
    background:#020617;
    color:white;
}

.navbar{
    display:flex;
    justify-content:space-between;
    align-items:center;
    padding:20px 40px;
    border-bottom:1px solid #1e293b;
}

.logo{
    font-size:24px;
    font-weight:bold;
    color:#818cf8;
}

.hero{
    text-align:center;
    padding:40px;
}

.hero h1{
    font-size:42px;
    margin-bottom:10px;
}

.hero p{
    color:#94a3b8;
}

.grid{
    display:grid;
    grid-template-columns:1fr 1fr;
    gap:25px;
    padding:30px;
}

.card{
    background:#1e293b;
    border-radius:18px;
    padding:25px;
    min-height:400px;
    box-shadow:0 0 20px rgba(0,0,0,0.4);
}

.card-title{
    background:#6366f1;
    display:inline-block;
    padding:8px 16px;
    border-radius:8px;
    font-weight:bold;
}

.drop-zone{
    border:2px dashed #475569;
    border-radius:15px;
    padding:45px;
    margin-top:30px;
    text-align:center;
    cursor:pointer;
}

.drop-zone:hover{
    background:#0f172a;
}

.preview img,
.result img{
    max-width:100%;
    border-radius:12px;
    margin-top:20px;
}

.btn{
    width:92%;
    margin:15px;
    padding:18px;
    font-size:20px;
    border:none;
    border-radius:12px;
    cursor:pointer;
    background:#475569;
    color:white;
}

.btn:hover{
    background:#64748b;
}

.result-text{
    margin-top:20px;
    font-size:18px;
}

.loading{
    margin-top:20px;
    font-size:20px;
    color:#38bdf8;
}

.footer{
    text-align:center;
    padding:20px;
    color:#64748b;
}

</style>

</head>

<body>

<div class="navbar">
    <div class="logo">🩻 XrayAI</div>
</div>

<div class="hero">
    <h1>Chest X-ray AI Detection</h1>
    <p>AI-powered chest X-ray analysis system</p>
</div>

<div class="grid">

    <!-- LEFT -->
    <div class="card">

        <div class="card-title">
            📤 Upload X-ray
        </div>

        <div class="drop-zone" id="dropZone">
            <p>Drop Image Here</p>
            <p>or Click to Upload</p>

            <input type="file" id="fileInput" hidden>
        </div>

        <div class="preview" id="preview"></div>

    </div>

    <!-- RIGHT -->
    <div class="card">

        <div class="card-title">
            🧠 AI Detection
        </div>

        <div class="loading" id="loading"></div>

        <div class="result" id="result"></div>

        <div class="result-text" id="resultText"></div>

    </div>

</div>

<center>

<button class="btn" onclick="predict()">
    🔍 Predict
</button>

<button class="btn" onclick="downloadPDF()">
    📄 Download PDF Report
</button>

</center>

<div class="footer">
    © 2026 XrayAI • AI Medical Imaging Demo
</div>

<script>

let selectedFile=null;

const dropZone=document.getElementById("dropZone");
const fileInput=document.getElementById("fileInput");

dropZone.onclick=()=>fileInput.click();

fileInput.onchange=e=>{
    selectedFile=e.target.files[0];
    showPreview(selectedFile);
};

dropZone.ondragover=e=>{
    e.preventDefault();
};

dropZone.ondrop=e=>{
    e.preventDefault();
    selectedFile=e.dataTransfer.files[0];
    showPreview(selectedFile);
};

function showPreview(file){

    const reader=new FileReader();

    reader.onload=e=>{
        preview.innerHTML=
        `<img src="${e.target.result}" width="350">`;
    };

    reader.readAsDataURL(file);
}

async function predict(){

    if(!selectedFile){
        alert("Please upload image first");
        return;
    }

    document.getElementById("loading").innerHTML=
        "⏳ AI is analyzing image...";

    const formData=new FormData();
    formData.append("file",selectedFile);

    const res=await fetch("/predict",{
        method:"POST",
        body:formData
    });

    const data=await res.json();

    document.getElementById("loading").innerHTML="";

    document.getElementById("result").innerHTML=
        `<img src="data:image/jpg;base64,${data.image}" width="400">`;

    let text="";

    if(data.predictions.length===0){

        text="<p style='color:#22c55e'><b>No abnormality detected</b></p>";

    }else{

        data.predictions.forEach(p=>{

            text+=`
            <div style="
                background:#334155;
                padding:12px;
                margin-top:10px;
                border-radius:10px;
            ">
                ${p.name} — <b>${p.conf}%</b>
            </div>
            `;
        });
    }

    document.getElementById("resultText").innerHTML=text;
}

function downloadPDF(){
    window.location="/download";
}

</script>

</body>
</html>
"""

# =========================================================
# API PREDICT
# =========================================================

@app.post("/predict")
async def predict(file: UploadFile = File(...)):

    # SAVE IMAGE
    with open("input.jpg", "wb") as buffer:
        shutil.copyfileobj(file.file, buffer)

    # OPTIMIZE IMAGE
    img = Image.open("input.jpg")
    img = img.convert("RGB")
    img.thumbnail((640,640))
    img.save("input.jpg", optimize=True, quality=85)

    # RUN AI
    result_img, predictions = run_prediction("input.jpg")

    # CREATE PDF
    generate_pdf(
        "input.jpg",
        result_img,
        predictions
    )

    # ENCODE RESULT IMAGE
    with open(result_img, "rb") as f:
        encoded = base64.b64encode(
            f.read()
        ).decode()

    return {
        "image": encoded,
        "predictions": predictions
    }

# =========================================================
# DOWNLOAD PDF
# =========================================================

@app.get("/download")
def download_pdf():

    return FileResponse(
        "report.pdf",
        media_type="application/pdf",
        filename="Xray_Report.pdf"
    )

# =========================================================
# RUN SERVER
# =========================================================

if __name__ == "__main__":

    port = int(os.environ.get("PORT", 8080))

    uvicorn.run(
        "main:app",
        host="0.0.0.0",
        port=port
    )